name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build and push Docker image
      env:
        DOCKER_USERNAME: ${{ secrets.fahadkamran2001 }}
        DOCKER_PASSWORD: ${{ secrets.dckr_pat_7-T0r1xkiiX2WXl1n3e4cULle2E }}
      run: |
        docker buildx create --use
        docker buildx build -t <fahadkamran2001>/CA3:latest --push .
